import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{js,ts,jsx,tsx,mdx}", "./components/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#95ccff",
        "surface-container-lowest": "#0a0f14",
        "on-tertiary": "#492900",
        "on-background": "#dee3ea",
        "inverse-primary": "#006399",
        "on-primary-container": "#003554",
        "on-surface-variant": "#bec7d3",
        "surface-container": "#1b2025",
        "surface-container-high": "#252a30",
        "on-error": "#690005",
        secondary: "#c4c7c9",
        "on-primary": "#003352",
        "on-primary-fixed-variant": "#004a75",
        error: "#ffb4ab",
        "on-error-container": "#ffdad6",
        "border-subtle": "#2F3336",
        "inverse-surface": "#dee3ea",
        "primary-fixed-dim": "#95ccff",
        "surface-container-low": "#171c21",
        "surface-container-highest": "#30353b",
        "on-secondary-container": "#b2b6b8",
        "surface-variant": "#30353b",
        "on-tertiary-container": "#4c2a00",
        "outline-variant": "#3f4851",
        "surface-bright": "#353a3f",
        "error-container": "#93000a",
        "on-secondary-fixed-variant": "#434749",
        "tertiary-fixed-dim": "#ffb86e",
        "primary-fixed": "#cde5ff",
        "on-secondary-fixed": "#181c1e",
        "secondary-container": "#434749",
        "on-surface": "#dee3ea",
        outline: "#89929c",
        tertiary: "#ffb86e",
        "on-secondary": "#2d3133",
        "tertiary-fixed": "#ffdcbd",
        "primary-container": "#1da1f2",
        "on-tertiary-fixed-variant": "#693c00",
        "surface-dim": "#0f1419",
        "text-dimmed": "#71767B",
        primary: "#95ccff",
        "inverse-on-surface": "#2c3136",
        background: "#0f1419",
        surface: "#0f1419",
        "on-primary-fixed": "#001d32",
        "secondary-fixed-dim": "#c4c7c9",
        "canvas-black": "#000000",
        "secondary-fixed": "#e0e3e5",
        "on-tertiary-fixed": "#2c1600",
        "tertiary-container": "#de8500",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "section-gap": "120px",
        "margin-mobile": "16px",
        gutter: "24px",
        "container-max": "1200px",
      },
      fontFamily: {
        "label-sm": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "display-xl-mobile": ["Geist", "sans-serif"],
        "display-xl": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["13px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-xl-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "display-xl": ["64px", { lineHeight: "72px", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
